name: .NET

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    name: test
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    steps:
      - uses: actions/checkout@v3
      - name: Setup
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: |
            3.1.x
            6.0.x
            7.0.x
    
      - name: Restore
        run: dotnet restore IT.Serialization.sln
    
      - name: Build
        run: dotnet build IT.Serialization.sln --configuration Release --no-restore 
    
      - name: Test
        run: dotnet test IT.Serialization.Tests/IT.Serialization.Tests.csproj --no-restore

  publish:
    needs: [build]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
            
      - name: Publish IT.Serialization.Json
        uses: pairbit/publish-nuget@v2.6.0
        with:
            PROJECT_FILE_PATH: IT.Serialization.Json/IT.Serialization.Json.csproj
            NUGET_KEY: ${{secrets.NUGET}}
            
      - name: Publish IT.Serialization.MemoryPack
        uses: pairbit/publish-nuget@v2.6.0
        with:
            PROJECT_FILE_PATH: IT.Serialization.MemoryPack/IT.Serialization.MemoryPack.csproj
            NUGET_KEY: ${{secrets.NUGET}}
          
      - name: Publish IT.Serialization.MessagePack
        uses: pairbit/publish-nuget@v2.6.0
        with:
            PROJECT_FILE_PATH: IT.Serialization.MessagePack/IT.Serialization.MessagePack.csproj
            NUGET_KEY: ${{secrets.NUGET}}
          
      - name: Publish IT.Serialization.Utf8Json
        uses: pairbit/publish-nuget@v2.6.0
        with:
            PROJECT_FILE_PATH: IT.Serialization.Utf8Json/IT.Serialization.Utf8Json.csproj
            NUGET_KEY: ${{secrets.NUGET}}
            
      - name: Publish IT.Serialization
        uses: pairbit/publish-nuget@v2.6.0
        with:
            PROJECT_FILE_PATH: IT.Serialization/IT.Serialization.csproj
            NUGET_KEY: ${{secrets.NUGET}}
            TAG_COMMIT: true
